### ISSUE TITLE
ModuleNotFoundError: No module named 'celery.apps'

### ISSUE THREAD

**Issue by encodingl** [lazzyfu/YaSQL#193]
```
(auditsql) [root@devops opsql]# celery worker -A opsql --loglevel=INFO --time-limit=7200 --concurrency=10 --uid=nginx
Traceback (most recent call last):
  File "/root/.virtualenvs/auditsql/lib/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
KeyError: 'Worker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.virtualenvs/auditsql/bin/celery", line 10, in <module>
  File "/root/.virtualenvs/auditsql/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
  File "/root/.virtualenvs/auditsql/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
  File "/root/.virtualenvs/auditsql/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
  File "/root/.virtualenvs/auditsql/lib/python3.6/site-packages/celery/bin/base.py", line 275, in execute_from_commandline
  File "/root/.virtualenvs/auditsql/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
  File "/root/.virtualenvs/auditsql/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
  File "/root/.virtualenvs/auditsql/lib/python3.6/site-packages/celery/bin/worker.py", line 223, in run_from_argv
  File "/root/.virtualenvs/auditsql/lib/python3.6/site-packages/celery/bin/base.py", line 238, in __call__
  File "/root/.virtualenvs/auditsql/lib/python3.6/site-packages/celery/bin/worker.py", line 252, in run
  File "/root/.virtualenvs/auditsql/lib/python3.6/site-packages/kombu/utils/objects.py", line 44, in __get__
  File "/root/.virtualenvs/auditsql/lib/python3.6/site-packages/celery/app/base.py", line 1100, in Worker
  File "/root/.virtualenvs/auditsql/lib/python3.6/site-packages/celery/app/base.py", line 1026, in subclass_with_self
  File "/root/.virtualenvs/auditsql/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
  File "/root/.virtualenvs/auditsql/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'celery.apps'
(auditsql) [root@devops opsql]# pwd
/data/web/opsql
(auditsql) [root@devops opsql]#
```

```
(auditsql) [root@devops opsql]# python -m pip freeze
aioredis==1.2.0
amqp==2.4.2
asgiref==2.3.2
asn1crypto==0.24.0
astroid==2.2.5
async-timeout==3.0.1
attrs==19.1.0
autobahn==19.2.1
Automat==0.7.0
bcrypt==3.1.6
billiard==3.5.0.5
celery==4.2.1
certifi==2019.3.9
cffi==1.12.2
channels==2.1.7
channels-redis==2.3.3
chardet==3.0.4
constantly==15.1.0
cryptography==2.6.1
daphne==2.2.5
DingtalkChatbot==1.3.0
Django==2.2.3
django-auth-ldap==1.7.0
django-celery-beat==1.4.0
django-celery-results==1.0.4
django-redis==4.10.0
django-stubs==1.0.2
django-timezone-field==3.0
djangorestframework==3.9.2
djangorestframework-stubs==0.3.0
et-xmlfile==1.0.1
gevent==1.4.0
greenlet==0.4.15
hiredis==1.0.0
humanfriendly==4.18
hyperlink==18.0.0
idna==2.8
incremental==17.5.0
isort==4.3.20
jdcal==1.4
kombu==4.4.0
lazy-object-proxy==1.4.1
mccabe==0.6.1
meld3==1.0.2
msgpack==0.6.1
mypy==0.720
mypy-extensions==0.4.1
mysql-replication==0.18
mysqlclient==1.3.13
openpyxl==2.6.1
paramiko==2.4.2
Pillow==5.4.1
pyasn1==0.4.5
pyasn1-modules==0.2.4
pycparser==2.19
PyHamcrest==1.9.0
pylint==2.3.1
PyMySQL==0.9.3
PyNaCl==1.3.0
python-crontab==2.3.6
python-dateutil==2.8.0
python-ldap==3.2.0
pytz==2018.9
redis==3.2.0
requests==2.21.0
simplejson==3.16.0
six==1.12.0
sqlparse==0.3.0
supervisor==4.0.4
Twisted==19.2.1
txaio==18.8.1
typed-ast==1.3.5
typing-extensions==3.7.4
urllib3==1.24.2
uWSGI==2.0.18
vine==1.2.0
wrapt==1.11.1
zope.interface==4.6.0
```

**Comment by lazzyfu** [comment]
![image](https://user-images.githubusercontent.com/14190782/62678663-ad23d700-b9e4-11e9-9bb2-3065e51731cf.png)
感觉像是python的虚拟环境没有生效，没有遇见过这个错误。按照wiki操作应该是没有问题的。使用supervisor管理启动试下

**Comment by lazzyfu** [comment]
或者检查下app的名称opsql，你是不是改成其他的了，导致找不到
一般是在/data/web/opsql/ 目录下执行/venv_py36/bin/celery worker -A opsql --loglevel=INFO --time-limit=7200 --concurrency=10 --uid=nginx  改成/venv_py36/bin/celery试下

**Comment by encodingl** [comment]
是的， python虚拟机改成"/root/.virtualenvs/auditsql了 ，相应的配置文件也修改了；app的名称是opsql；supervisor也是报同样的错误；我改回/venv_py36 再试试

**Comment by encodingl** [comment]
我把python虚拟机改成/venv_py36 就可以正常运行了，可以咨询一下这是哪里限制的么？

**Comment by lazzyfu** [comment]
应该没有，可能是哪个服务的配置文件写了(比如: uwsgi, nginx等)，可以检查下，我记不太清楚了。代码不会写死

**Comment by chenyaqiao0505** [comment]
请问下，问题解决了吗？我也遇到了相同的问题，估计出错地方相同。网上找遍了，就你这个帖子跟我问题一致。麻烦解答下，不胜感激。

**Comment by lazzyfu** [comment]
把python虚拟机改成/venv_py36 就可以正常运行了
看下上面的回复，请按照文档操作，谢谢
